In [ ]:
!pip install numpy

In [3]:
import numpy as np

# Array Initialization

In [7]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(A, end='\n\n')

Af = np.array([1, 2, 3], dtype=float) 

print(Af)

[[1 2 3]
 [4 5 6]]

[1. 2. 3.]


In [8]:
np.arange(0, 1, 0.2)        

np.linspace(0, 2*np.pi, 4)  

A = np.zeros((2, 3))        

print(A.shape)             

(2, 3)


# Numpy arrays are mutable

In [6]:
A = np.zeros((2, 2))


C = A
C[0, 0] = 1

print(A)


[[1. 0.]
 [0. 0.]]


# Array Attributes

In [11]:
a = np.arange(10).reshape((2, 5))

print(a.ndim, end="\n\n")

print(a.shape, end="\n\n")

print(a.size, end="\n\n")

print(a.T, end="\n\n")

print(a.dtype, end="\n\n")       

2

(2, 5)

10

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

int64



# Basic Operations

In [12]:
a = np.arange(4)  # array([0, 1, 2, 3])

b = np.array([2, 3, 2, 4])

print(a * b, end="\n\n")

print(b - a, end="\n\n")

c = [2, 3, 4, 5]
print(a * c, end="\n\n")

[ 0  3  4 12]

[2 2 0 1]

[ 0  3  8 15]



# Vector Operations

In [13]:
# Example vectors
u = [1, 2, 3]
v = [1, 1, 1]

# Inner product
inner = np.inner(u, v) 

# Outer product
outer = np.outer(u, v) 

# Dot product
dot = np.dot(u, v)

print(inner, end="\n\n")

print(outer, end="\n\n")

print(dot, end="\n\n")

6

[[1 1 1]
 [2 2 2]
 [3 3 3]]

6



# Matrix Operations

In [15]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# np.add(A, B): Adds matrices A and B element-wise
add_result = np.add(A, B)
print("np.add(A, B):\n", add_result, end="\n\n")

# np.subtract(A, B): Subtracts matrix B from matrix A element-wise
subtract_result = np.subtract(A, B)
print("np.subtract(A, B):\n", subtract_result, end="\n\n")

# np.multiply(A, B): Multiplies matrices A and B element-wise
multiply_result = np.multiply(A, B)
print("np.multiply(A, B):\n", multiply_result, end="\n\n")

# np.divide(A, B): Divides matrix A by matrix B element-wise
divide_result = np.divide(A, B)
print("np.divide(A, B):\n", divide_result, end="\n\n")

# np.dot(A, B): Computes the dot product of matrices A and B
dot_result = np.dot(A, B)
print("np.dot(A, B):\n", dot_result, end="\n\n")

# np.matmul(A, B): Performs matrix multiplication (supports 2D arrays)
matmul_result = np.matmul(A, B)
print("np.matmul(A, B):\n", matmul_result, end="\n\n")


# np.transpose(A): Transposes matrix A (swaps rows and columns)
transpose_result = np.transpose(A)
print("np.transpose(A):\n", transpose_result, end="\n\n")


# np.identity(n): Creates an n x n identity matrix
identity_result = np.identity(2)
print("np.identity(2):\n", identity_result, end="\n\n")

# np.trace(A): Computes the trace of matrix A (sum of diagonal elements)
trace_result = np.trace(A)
print("np.trace(A):\n", trace_result, end="\n\n")

np.add(A, B):
 [[ 6  8]
 [10 12]]

np.subtract(A, B):
 [[-4 -4]
 [-4 -4]]

np.multiply(A, B):
 [[ 5 12]
 [21 32]]

np.divide(A, B):
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

np.dot(A, B):
 [[19 22]
 [43 50]]

np.matmul(A, B):
 [[19 22]
 [43 50]]

np.transpose(A):
 [[1 3]
 [2 4]]

np.identity(2):
 [[1. 0.]
 [0. 1.]]

np.trace(A):
 5



# 1-D Array Slicing

In [17]:
# Generate a 1-D array
a = np.array([0.25, 0.56, 0.98, 0.13, 0.72])

print(a[2:], end="\n\n") # 2 is the starting index (inclusive) and the end is the end of the array

print(a[1:4], end="\n\n") # 1 is the starting index, 4 is the ending index (exclusive)

print(a[::2], end="\n\n") # 2 is the step size

[0.98 0.13 0.72]

[0.56 0.98 0.13]

[0.25 0.98 0.72]



In [19]:
# Generate a 1-D array
a = np.array([0.25, 0.56, 0.98, 0.13, 0.72])

# Select elements in reverse order
print(a[::-1], end="\n\n")  # -1 here is the step size and the blank before the colon means start from the beginning

# Select elements from index 4 to 1 in reverse order
print(a[4:0:-1], end="\n\n")  # 4 is the starting index, 0 is the ending index (exclusive), and -1 is the step size 

# Select the last element (negative indexing)
print(a[-1], end="\n\n")

# Select the second to last element
print(a[-2], end="\n\n")

[0.72 0.13 0.98 0.56 0.25]

[0.72 0.13 0.98 0.56]

0.72

0.13



# 2-D Array Slicing

In [20]:
a = np.array([[ 0.25,  0.56,  0.98,  0.13,  0.72],
              [ 0.43,  0.15,  0.67,  0.89,  0.24],
              [ 0.91,  0.78,  0.64,  0.38,  0.55],
              [ 0.19,  0.82,  0.13,  0.29,  0.71]])

# Select the third row, all columns
print(a[2, :], end="\n\n")

# Select the 2nd and 3rd rows, all columns
print(a[1:3], end="\n\n")

[0.91 0.78 0.64 0.38 0.55]

[[0.43 0.15 0.67 0.89 0.24]
 [0.91 0.78 0.64 0.38 0.55]]



In [21]:
# Select rows 1 through 3 (exclusive of 3), columns 1 through 4 (exclusive of 4)
print(a[1:3, 1:4], end="\n\n")


# Select rows in reverse order, every other column
print(a[::-1, ::2], end="\n\n") # -1 is the step size for rows, 2 is the step size for columns

# Select the last element from the last row (negative indexing)
print(a[-1, -1], end="\n\n")

[[0.15 0.67 0.89]
 [0.78 0.64 0.38]]

[[0.19 0.13 0.71]
 [0.91 0.64 0.55]
 [0.43 0.67 0.24]
 [0.25 0.98 0.72]]

0.71



# Reshaping

In [23]:
# Create a 1D array of size 12
a = np.arange(12)
print("Original array:")
print(a, end="\n\n")

# Reshape the array to 3x4
reshaped = a.reshape(3, 4)
print("Reshaped array (3x4):")
print(reshaped, end="\n\n")

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array (3x4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



In [27]:
# Reshape Example
a = np.arange(12)

print(a, end="\n\n")

# Valid reshaping
reshaped = a.reshape(3, 4)
print(reshaped, end="\n\n")

# Invalid reshaping (raises an error)
invalid = a.reshape(3, 5)  # ValueError: cannot reshape array

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



ValueError: cannot reshape array of size 12 into shape (3,5)

# Seeds in NumPy

In [29]:
# Set the seed for reproducibility
np.random.seed(42)
print(np.random.rand(2,3), end = "\n\n")    
# array([[0.37454012, 0.95071431, 0.73199394],
#        [0.59865848, 0.15601864, 0.15599452]])

# seed again
np.random.seed(42)
print(np.random.rand(2,3))
# array([[0.37454012, 0.95071431, 0.73199394],
#        [0.59865848, 0.15601864, 0.15599452]])

# Generates the same numbers every time after setting the seed

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


# Masking

### Masking with AND condition

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
        
# Masking with AND condition
mask = (arr > 2) & (arr < 5)
print("Mask:\n", mask, end="\n\n")  

masked_array = arr[mask]
print("Masked Array:\n", masked_array, end="\n\n")

# you can directly use the mask to index the array
masked_array = arr[(arr > 2) & (arr < 5)]
print("Masked Array:\n", masked_array, end="\n\n")

Mask:
 [False False  True  True False False]

Masked Array:
 [3 4]



### Masking with OR condition

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Masking with OR condition
mask = (arr < 2) | (arr > 5)
print("Mask:\n", mask, end="\n\n")

masked_array = arr[mask]
print("Masked Array:\n", masked_array, end="\n\n")

# you can directly use the mask to index the array
masked_array = arr[(arr < 2) | (arr > 5)]
print("Masked Array:\n", masked_array, end="\n\n")


Mask:
 [ True False False False False  True]

Masked Array:
 [1 6]



# Vectorization

In [2]:
import numpy as np
from time import time


NO_OF_ELEMENTS = int(1e6) 

w = np.random.rand(NO_OF_ELEMENTS)
x = np.random.rand(NO_OF_ELEMENTS)
c = np.zeros(NO_OF_ELEMENTS)

start_time = time()
c = np.dot(w, x) # Vectorized implementation
print("Vectorized time:", time() - start_time)

start_time = time()
for i in range(NO_OF_ELEMENTS): # Non-vectorized implementation
    c += w[i] * x[i]

print("Non-vectorized time:", time() - start_time)

Vectorized time: 0.00461125373840332
Non-vectorized time: 0.355053186416626


The Non-Vectorized Implementation takes almost a 100 times more time than the Vectorized Implementation.